### ISSUE TITLE
New RiTa library testing

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#198]
Please test new website (this is top priority): http://rednoise.org/rita/

1. Check all links on website.
2. Check all links on download page.
3. Step carefully through ALL 'quickstart' installation instructions.
4. Download lib from [npm](https://www.npmjs.com/package/rita) and test instructions on npm README
5. Test installation of library in Processing 3.0
6. Check all 'Selected Project' links on home page
7. Check all links on gallery page.
8. Think of other things to test... 

Keep a simple list of your tests, so that we can re-use it...

**Comment by CyrusSUEN** [comment]
- [x] Check all links on website.
http://rednoise.org/rita/index.php has menu bar on the very top
http://rednoise.org/rita/ does not have menu bar
Reference page: [toCharArray()](http://rednoise.org/rita/reference/RiString/toCharArray/index.php) 404

- [x] Check all links on download page.
- [x] Step carefully through ALL 'quickstart' installation instructions.
Perhaps [In node.js (via github)](https://github.com/dhowe/RiTaJS#with-nodejs-and-npm) should link to [RiTaJS/README.node.md](https://github.com/dhowe/RiTaJS/blob/master/README.node.md#in-nodejs)

- [x] Download lib from npm and test instructions on npm README
[RiTa npm page](https://www.npmjs.com/package/rita): [the link](http://rednoise.org/rita/img/RiTa-logo3.png) to the RiTa logo image is broken

- [x] Test installation of library in Processing 3.0
- [x] Check all 'Selected Project' links on home page
- [x] Check all links on gallery page.
Gallery page: [SpinState](http://www.rednoise.org/rita/sketches/spinstate/) 404

- [x] Think of other things to test...
Maybe we can include the examples from Quickstart page to rita.zip/examples so that we and the users can easily test and experiment with the examples

**Comment by dhowe** [comment]
phone looks excellent, thanks…
let me know what I owe you for the parts
DH

**Comment by CyrusSUEN** [comment]
One more thing: links to the methods of [RiText](http://rednoise.org/rita/reference/RiText.php) are all 404

**Comment by dhowe** [comment]
DH: should be fixed, please verify

**Comment by CyrusSUEN** [comment]
> please verify

A few links still broken, here is a fix: https://github.com/dhowe/RiTa/pull/206/files

**Comment by dhowe** [comment]
Merged. And now?

**Comment by CyrusSUEN** [comment]
> And now?

Those affected broken links in RiText still seems inaccessible.

rita/examples folder from [RiTa-complete](https://rednoise.org/rita/rita.zip) is empty.
https://github.com/dhowe/RiTa/issues/204

**Comment by dhowe** [comment]
Yes, I have not pushed new changes live yet. Can you view the website on your local machine?
/RiTa/web/index.php
?

**Comment by CyrusSUEN** [comment]
> Can you view the website on your local machine?

Yes, I can.

**Comment by dhowe** [comment]
and????

**Comment by CyrusSUEN** [comment]
all done. closing

**Comment by dhowe** [comment]
Please re-run full test set on v1.1.21

**Comment by CyrusSUEN** [comment]
Problem found on RiTa npm
This happens only on Windows platform.
```
PS D:\Development\npmRiTa\node_modules\rita> npm test

> rita@1.1.21 test D:\Development\npmRiTa\node_modules\rita
> gulp test-npm

[18:54:03] Using gulpfile D:\Development\npmRiTa\node_modules\rita\gulpfile.js
[18:54:03] Starting 'clean'...
[18:54:03] Finished 'clean' after 5.88 ms
[18:54:03] Starting 'build-nolex'...
[18:54:03] Starting 'build-lex'...
[18:54:04] Finished 'build-nolex' after 30 ms
[18:54:04] Finished 'build-lex' after 16 ms
[18:54:04] Starting 'build'...
[18:54:04] Finished 'build' after 9.01 μs
[18:54:04] Starting 'test-npm'...
[18:54:04] Starting 'test-only'...
[INFO] Source: lib/rita.js
[18:54:04] Finished 'test-npm' after 192 ms
[INFO] RiTaJS.version [1.1.21]
[INFO] Testing LibraryStructure
[INFO] Testing RiTaEvent
[INFO] Testing RiString
[INFO] Testing RiTa
[INFO] RiTa-tests: skipping lancaster tests
[INFO] Testing RiGrammar
[INFO] Testing RiMarkov
[INFO] Testing UrlLoading
{ [Error: Unexpected token <] message: 'Unexpected token <' }
{ files: 0,
  assertions: 0,
  failed: 0,
  passed: 0,
  runtime: 0,
  tests: 150,
  coverage:
   { files: 0,
     statements: { covered: 0, total: 0 },
     branches: { covered: 0, total: 0 },
     functions: { covered: 0, total: 0 },
     lines: { covered: 0, total: 0 } } }
[18:54:07] Finished 'test-only' after 3.32 s
```

**Comment by CyrusSUEN** [comment]
> 2 Problems found on RiTa npm

Requires local server of RiTaJS repo setup in "http://localhost/ritajs/" to run the test. 
Fixed by disabling affected tests: https://github.com/dhowe/RiTaJS/commit/2ac7eeb7f0c70d8fa45dfbf3837adfa071d04c5e
